// Generated by Wrangler on Sat Jul 06 2024 17:06:49 GMT+0800 (中国标准时间)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	PASSWORD: string; // 访问密码
	GITHUB_TOKEN: string; // github token
}
